version: "3"

services:
  app:
    container_name: portfolio-next
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    tty: true
    ports:
      - "3000:3000"